# Generated by Django 4.2.6 on 2023-10-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kirill_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Birthday', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
